name: Torela
url: https://torela.ee
api: https://api.torela.ee
permalink: /:year/:month/:title.html
ga: G-JJDTS38SP7
email: tore@torela.ee
address: Ristiku 12, Tallinn
phone: 5661 1711
iban: EE477700771003581431
