services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: torela
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}

  torela:
    build: .
    image: torela-torela
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - PASSWORD
